import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { chainConfig } from "@/lib/solana";
import { WalletProviders } from "@/components/WalletProviders";
import { ConfigProvider } from "@/components/ConfigContext";
import { Nav } from "@/components/Nav";
import { SiteFooter } from "@/components/SiteFooter";
import { THEME_SCRIPT } from "@/components/ThemeToggle";

const display = Plus_Jakarta_Sans({ subsets: ["latin"], weight: ["600", "700", "800"], variable: "--font-display-face", display: "swap" });
const ui = Inter({ subsets: ["latin"], weight: ["400", "500", "600", "700"], variable: "--font-ui", display: "swap" });
const mono = JetBrains_Mono({ subsets: ["latin"], weight: ["400", "500"], variable: "--font-mono-face", display: "swap" });

export const viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FAF9FE" },
    { media: "(prefers-color-scheme: dark)", color: "#0F0D24" },
  ],
};

// Blank or scheme-less values make `new URL` throw, and this runs at import time, so a
// mistyped variable would stop the site booting rather than just spoiling a link preview.
const rawSite = process.env.NEXT_PUBLIC_SITE_URL?.trim();
const SITE_URL = rawSite && /^https?:\/\//i.test(rawSite) ? rawSite : "https://project-takeover.com";
const TITLE = "Project: Takeover — think you'd run it better? Buy it.";
const DESCRIPTION =
  "Buy Solana projects outright, not by the bag. Memecoin authorities, pump.fun coin ownership, whole sites and communities — handed over on chain, with nobody holding the money but the code. Built something? Sell it.";

/**
 * The site had no Open Graph tags at all, so a pasted link showed as bare text: no image,
 * no title card, nothing. For a project whose distribution is people posting links on X
 * and Telegram, that was the difference between a post that gets looked at and one that
 * does not. The card is generated by scripts/brand.mjs from the same mark as everything
 * else, at 1200x630 — the shape X, Discord and Telegram actually render.
 */
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: "Project: Takeover",
    title: TITLE,
    description: DESCRIPTION,
    images: [{ url: "/brand/og.png", width: 1200, height: 630, alt: "Project: Takeover — think you'd run it better? Buy it." }],
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    images: ["/brand/og.png"],
  },
};
export const dynamic = "force-dynamic";

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // Chain-backed, not env-backed: this config is what the browser builds its buy
  // transactions from, so a stale treasury here means every purchase is rejected.
  const config = await chainConfig();
  return (
    <html lang="en" className={`${display.variable} ${ui.variable} ${mono.variable}`} suppressHydrationWarning>
      <head>
        {/* Stamps data-theme before the body paints. Any later and dark-mode visitors
            get a white flash on every navigation. */}
        <script dangerouslySetInnerHTML={{ __html: THEME_SCRIPT }} />
      </head>
      <body className="min-h-screen antialiased">
        <ConfigProvider config={config}>
          <WalletProviders rpcUrl={config.rpcUrl}>
            <Nav />
            <main>{children}</main>
            <SiteFooter config={config} />
          </WalletProviders>
        </ConfigProvider>
      </body>
    </html>
  );
}
